package ru.netscope.feature.monitor

import android.telephony.TelephonyManager
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.*
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import ru.netscope.core.telephony.model.*

@Composable fun MonitorScreen(viewModel: MonitorViewModel, sessionId: Long, onFaqClick: () -> Unit = {}) { val state by viewModel.uiState.collectAsStateWithLifecycle(); val beginner by viewModel.beginnerMode.collectAsStateWithLifecycle(); LaunchedEffect(sessionId) { viewModel.start(sessionId) }; val current = state.current; val compact = !beginner; Column(Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background).padding(if (compact) 8.dp else 16.dp)) { if (current?.isDataComplete == false) { Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.errorContainer), modifier = Modifier.fillMaxWidth()) { Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.padding(12.dp)) { Text(stringResource(R.string.data_incomplete), modifier = Modifier.weight(1f)); TextButton(onClick = onFaqClick) { Text(stringResource(R.string.faq)) } } }; Spacer(Modifier.height(8.dp)) }; LazyColumn(verticalArrangement = Arrangement.spacedBy(if (compact) 8.dp else 12.dp)) { item { NetworkTypeChip(current, beginner, state.carriers.size > 1) }; item { if (compact) Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) { SignalGaugeCard(current, beginner, Modifier.weight(1f)); CellIdentityCard(current, beginner, Modifier.weight(1f)) } else Column(verticalArrangement = Arrangement.spacedBy(12.dp)) { SignalGaugeCard(current, beginner); CellIdentityCard(current, beginner) } }; item { CarrierAggregationRow(state.carriers, beginner) }; item { SignalHistoryChart(state.history) } } } }
@Composable fun SignalGaugeCard(cell: CellMeasurement?, beginner: Boolean, modifier: Modifier = Modifier) { InfoCard("Сигнал", modifier) { Metric("RSRP", cell?.rsrp?.let { "$it dBm" } ?: "—", signalColor(cell?.rsrp), beginner, R.string.explain_rsrp); Metric("RSRQ", cell?.rsrq?.let { "$it dB" } ?: "—", MaterialTheme.colorScheme.primary, beginner, R.string.explain_rsrq); Metric("SINR", cell?.sinr?.let { "$it dB" } ?: "—", MaterialTheme.colorScheme.primary, beginner, R.string.explain_sinr) } }
@Composable fun NetworkTypeChip(cell: CellMeasurement?, beginner: Boolean, hasCarrierAggregation: Boolean = false) { val type = when (cell?.networkType) { TelephonyManager.NETWORK_TYPE_GSM, TelephonyManager.NETWORK_TYPE_GPRS, TelephonyManager.NETWORK_TYPE_EDGE -> "2G"; TelephonyManager.NETWORK_TYPE_UMTS, TelephonyManager.NETWORK_TYPE_HSDPA, TelephonyManager.NETWORK_TYPE_HSPA -> "3G"; TelephonyManager.NETWORK_TYPE_LTE -> if (hasCarrierAggregation) "4G+" else "4G"; TelephonyManager.NETWORK_TYPE_NR -> if (cell.nsaGroupId != null) "5G NSA" else "5G SA"; else -> "—" }; InfoCard("Тип сети", Modifier.fillMaxWidth()) { Row(verticalAlignment = Alignment.CenterVertically) { Surface(shape = RoundedCornerShape(50), color = MaterialTheme.colorScheme.primaryContainer) { Text(type, Modifier.padding(horizontal = 14.dp, vertical = 7.dp), fontWeight = FontWeight.Bold) }; if (type == "5G NSA") { Text("  LTE anchor + NR"); ExplainIcon(beginner, R.string.explain_nsa) } } } }
@Composable fun CarrierAggregationRow(carriers: List<ComponentCarrier>, beginner: Boolean) { InfoCard("CA", Modifier.fillMaxWidth()) { Row(verticalAlignment = Alignment.CenterVertically) { Text("Component carriers"); ExplainIcon(beginner, R.string.explain_ca) }; Row(Modifier.horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(8.dp)) { if (carriers.isEmpty()) Text("—"); carriers.forEachIndexed { index, carrier -> Surface(color = MaterialTheme.colorScheme.secondaryContainer, shape = RoundedCornerShape(8.dp)) { Column(Modifier.padding(horizontal = 12.dp, vertical = 8.dp)) { Text("CC${index + 1}", fontWeight = FontWeight.Bold); Text("band ${carrier.downlinkChannelNumber ?: "—"}"); Text("${carrier.downlinkBandwidthKhz?.let { it / 1000 } ?: "—"} MHz") } } } } } }
@Composable fun CellIdentityCard(cell: CellMeasurement?, beginner: Boolean, modifier: Modifier = Modifier) { InfoCard("Идентификатор соты", modifier) { Text("Оператор: ${cell?.operatorName ?: "—"}"); Text("MCC/MNC: ${cell?.mcc ?: "—"}/${cell?.mnc ?: "—"}"); Text("LAC: ${cell?.lac ?: "—"}    CID: ${cell?.cid ?: "—"}"); Row(verticalAlignment = Alignment.CenterVertically) { Text("PCI: ${cell?.pci ?: "—"}    TAC: ${cell?.tac ?: "—"}"); ExplainIcon(beginner, R.string.explain_pci) } } }
@Composable fun SignalHistoryChart(history: List<CellMeasurement>) { InfoCard("RSRP за последние 5 минут", Modifier.fillMaxWidth()) { Canvas(Modifier.fillMaxWidth().height(150.dp)) { if (history.size < 2) return@Canvas; val values = history.mapNotNull { it.rsrp }; if (values.size < 2) return@Canvas; val min = minOf(-120, values.minOrNull() ?: -120).toFloat(); val max = maxOf(-50, values.maxOrNull() ?: -50).toFloat(); val path = Path(); values.forEachIndexed { index, value -> val x = size.width * index / values.lastIndex.coerceAtLeast(1); val y = size.height * (1f - (value - min) / (max - min)); if (index == 0) path.moveTo(x, y) else path.lineTo(x, y) }; drawPath(path, Color(0xFF2E7D32), style = Stroke(3.dp.toPx(), cap = StrokeCap.Round)); drawLine(Color.LightGray, Offset(0f, size.height - 1), Offset(size.width, size.height - 1)) } } }
@Composable private fun InfoCard(title: String, modifier: Modifier, content: @Composable ColumnScope.() -> Unit) { Card(modifier = modifier, colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceContainer)) { Column(Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Text(title, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold); content() } } }
@Composable private fun Metric(name: String, value: String, color: Color, beginner: Boolean, explanation: Int) { var expanded by remember { mutableStateOf(false) }; Row(verticalAlignment = Alignment.CenterVertically) { Text(name, fontWeight = FontWeight.Medium, modifier = Modifier.weight(1f)); Text(value, color = color, fontWeight = FontWeight.Bold); ExplainIcon(beginner, explanation) { expanded = !expanded } }; AnimatedVisibility(beginner && expanded) { Text(stringResource(explanation), style = MaterialTheme.typography.bodySmall) } }
@Composable private fun ExplainIcon(show: Boolean, explanation: Int, onClick: () -> Unit = {}) { if (show) Text("ⓘ", modifier = Modifier.padding(start = 6.dp).size(24.dp).clickable(onClick = onClick), color = MaterialTheme.colorScheme.primary) }
private fun signalColor(rsrp: Int?): Color = when { rsrp == null -> Color.Gray; rsrp > -80 -> Color(0xFF2E7D32); rsrp >= -100 -> Color(0xFFF9A825); else -> Color(0xFFC62828) }
